### ISSUE TITLE
Stack Smashing running ROSCore with WSL

### ISSUE THREAD

**Issue by tjsaunders** [gavanderhoorn/getifaddrs_preload#1]
Running ROSCore with WSL using getifaddrs from here with LD_PRELOAD appears to start correctly, until it fails with:

```
*** stack smashing detected ***: /usr/bin/python terminated Aborted (core dumped)
```

Fresh install of WSL. Fresh install of ROS.

**Comment by gavanderhoorn** [comment]
Would be great if you could add some more detail:
- build nr of Win10
- Ubuntu root fs version (`lsb_release -a`)
- version of ROS

**Comment by tjsaunders** [comment]
Sorry, not used to all of this:
Windows Build Number: Version 1607 Build 14393.321
Ubuntu 16.04.1 LTS
Unsure of ROS version. rosversion -d gives "unknown" but i'm running kinetic, and when i installed it i tried to get the newest version

Thanks for this again.

**Comment by gavanderhoorn** [comment]
To get back to this: this is most likely a problem with the way the code sets up the various `struct`s.

But seeing as build 14965 finally added support for interface enumeration (and some other parts that were missing), I'm going to close this as `wontfix`. It's no longer needed. `roscore` and all other ROS tools should work without the preload trick.
